# -*- coding: utf-8 -*-
"""RED 3 MLP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ji9jER7hDSAhIb4QHkm7JVOz5OZLVUFE
"""

# CELDA 1
# Objetivo: imports y GPU ready.

import os, json, random
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd

import torch
import torch.nn as nn
import torch.nn.functional as F

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, f1_score, accuracy_score

# CELDA 2
# Objetivo: config FINAL (labels + features congelados).

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("DEVICE:", DEVICE)

MODEL_VERSION = "red3_v1"
FEATURE_SCHEMA_VERSION = 1
WINDOWS_DAYS = [7, 30]

STYLES = [
    "PRACTICO_APLICADO",
    "MAGISTRAL_ESTRUCTURADO",
    "EVALUATIVO",
    "TECNOLOGICO_INNOVADOR",
    "REFLEXIVO_ITERATIVO",
]
STYLE_TO_IDX = {s: i for i, s in enumerate(STYLES)}

FEATURES = [
    # Uso del sistema
    ("active_days_7d", "int"),
    ("active_days_30d", "int"),
    ("sessions_7d", "int"),
    ("sessions_30d", "int"),
    # Chat
    ("chat_msgs_7d", "int"),
    ("chat_msgs_30d", "int"),
    ("chat_avg_len_30d", "float"),  # longitud promedio (>=20)
    ("chat_intent_rubric_ratio_30d", "float"),
    ("chat_intent_eval_ratio_30d", "float"),
    ("chat_intent_practice_ratio_30d", "float"),
    ("chat_intent_explain_ratio_30d", "float"),
    # PDC
    ("pdc_generated_7d", "int"),
    ("pdc_generated_30d", "int"),
    ("pdc_has_rubric_ratio_30d", "float"),
    ("pdc_has_eval_ratio_30d", "float"),
    ("pdc_practice_ratio_30d", "float"),
    ("pdc_theory_ratio_30d", "float"),
    ("pdc_production_ratio_30d", "float"),
    # Biblioteca PDC
    ("pdc_uploads_30d", "int"),
    ("pdc_downloads_30d", "int"),
    ("pdc_deletes_30d", "int"),
    ("pdc_iterative_index_30d", "float"),
    # Recursos/tech
    ("resources_suggested_30d", "int"),
    ("resource_tech_ratio_30d", "float"),
    # Dimensiones
    ("dim_saber_avg_30d", "float"),
    ("dim_hacer_avg_30d", "float"),
    ("dim_ser_avg_30d", "float"),
    ("dim_decidir_avg_30d", "float"),
    # Aceptación/fricción implícita
    ("approval_ratio_30d", "float"),
    ("friction_ratio_30d", "float"),
]

FEATURE_NAMES = [n for n, _ in FEATURES]
FEATURE_TYPES = {n: t for n, t in FEATURES}

INPUT_DIM = len(FEATURE_NAMES)
NUM_CLASSES = len(STYLES)

print("INPUT_DIM:", INPUT_DIM, "NUM_CLASSES:", NUM_CLASSES)

# CELDA 3
# Objetivo: helpers (clamp, softmax, JS, ECE).

def clamp01(x: float) -> float:
    return float(max(0.0, min(1.0, x)))

def softmax_np(x: np.ndarray) -> np.ndarray:
    x = x - np.max(x)
    e = np.exp(x)
    return e / np.sum(e)

def jensen_shannon(p: np.ndarray, q: np.ndarray, eps: float = 1e-12) -> float:
    p = np.clip(p, eps, 1.0)
    q = np.clip(q, eps, 1.0)
    p = p / p.sum()
    q = q / q.sum()
    m = 0.5 * (p + q)
    kl_pm = np.sum(p * np.log(p / m))
    kl_qm = np.sum(q * np.log(q / m))
    return float(0.5 * (kl_pm + kl_qm))

def expected_calibration_error(probs: np.ndarray, y_true: np.ndarray, n_bins: int = 12) -> float:
    conf = probs.max(axis=1)
    pred = probs.argmax(axis=1)
    acc = (pred == y_true).astype(np.float32)

    bins = np.linspace(0.0, 1.0, n_bins + 1)
    ece = 0.0
    for i in range(n_bins):
        lo, hi = bins[i], bins[i+1]
        mask = (conf >= lo) & (conf < hi)
        if mask.sum() == 0:
            continue
        bin_acc = float(acc[mask].mean())
        bin_conf = float(conf[mask].mean())
        ece += (mask.sum() / len(conf)) * abs(bin_acc - bin_conf)
    return float(ece)

# CELDA 4
# Objetivo: generador sintético FINAL (features agregadas coherentes + approval/friction).

def gen_one_sample() -> Dict[str, float]:
    active_days_30d = np.random.randint(0, 31)
    active_days_7d = min(active_days_30d, np.random.randint(0, 8))

    sessions_30d = int(np.random.poisson(lam=max(0.1, active_days_30d / 2)))
    sessions_7d = min(sessions_30d, int(np.random.poisson(lam=max(0.1, active_days_7d / 2))))

    chat_msgs_30d = int(np.random.poisson(lam=max(0.1, sessions_30d * 2)))
    chat_msgs_7d = min(chat_msgs_30d, int(np.random.poisson(lam=max(0.1, sessions_7d * 2))))
    chat_avg_len_30d = float(max(20.0, np.random.normal(loc=220, scale=80)))

    # intents ratios (dirichlet)
    intent_raw = np.random.dirichlet(alpha=[1.2, 1.2, 1.2, 1.2])
    chat_intent_rubric_ratio_30d = float(intent_raw[0])
    chat_intent_eval_ratio_30d = float(intent_raw[1])
    chat_intent_practice_ratio_30d = float(intent_raw[2])
    chat_intent_explain_ratio_30d = float(intent_raw[3])

    # PDC
    pdc_generated_30d = int(np.random.poisson(lam=max(0.05, sessions_30d / 3)))
    pdc_generated_7d = min(pdc_generated_30d, int(np.random.poisson(lam=max(0.05, sessions_7d / 3))))

    pdc_has_rubric_ratio_30d = float(np.random.beta(a=1.2, b=1.8)) if pdc_generated_30d > 0 else 0.0
    pdc_has_eval_ratio_30d = float(np.random.beta(a=1.2, b=1.8)) if pdc_generated_30d > 0 else 0.0

    structure = np.random.dirichlet(alpha=[1.3, 1.3, 1.0]) if pdc_generated_30d > 0 else np.array([0.0, 0.0, 0.0])
    pdc_practice_ratio_30d = float(structure[0])
    pdc_theory_ratio_30d = float(structure[1])
    pdc_production_ratio_30d = float(structure[2])

    # Biblioteca PDC
    pdc_uploads_30d = int(np.random.poisson(lam=max(0.0, pdc_generated_30d / 2)))
    pdc_downloads_30d = int(np.random.poisson(lam=max(0.0, pdc_generated_30d / 2)))
    pdc_deletes_30d = int(np.random.binomial(n=max(1, pdc_uploads_30d), p=0.15)) if pdc_uploads_30d > 0 else 0

    denom = max(1, pdc_uploads_30d + pdc_downloads_30d + pdc_deletes_30d)
    pdc_iterative_index_30d = clamp01((pdc_uploads_30d + pdc_deletes_30d) / denom)

    # Recursos/tech
    resources_suggested_30d = int(np.random.poisson(lam=max(0.0, chat_msgs_30d / 10)))
    resource_tech_ratio_30d = float(np.random.beta(a=1.0, b=2.0)) if resources_suggested_30d > 0 else 0.0

    # Dimensiones
    dims = np.random.dirichlet(alpha=[1.1, 1.1, 1.1, 1.1]) if (pdc_generated_30d + chat_msgs_30d) > 0 else np.array([0.0, 0.0, 0.0, 0.0])
    dim_saber_avg_30d = float(dims[0])
    dim_hacer_avg_30d = float(dims[1])
    dim_ser_avg_30d = float(dims[2])
    dim_decidir_avg_30d = float(dims[3])

    # Aceptación/fricción implícita (coherente: más fricción si chats altos y baja aprobación)
    base_friction = clamp01(float(np.random.beta(1.2, 3.0)))
    base_approval = clamp01(float(np.random.beta(2.5, 1.6)))

    # si chat_intent_eval/practice altos, tiende a haber más “insistencia” (proxy)
    insist = clamp01(0.5 * chat_intent_eval_ratio_30d + 0.5 * chat_intent_practice_ratio_30d)
    friction_ratio_30d = clamp01(base_friction + 0.25 * insist)
    approval_ratio_30d = clamp01(base_approval - 0.20 * friction_ratio_30d)

    return {
        "active_days_7d": int(active_days_7d),
        "active_days_30d": int(active_days_30d),
        "sessions_7d": int(sessions_7d),
        "sessions_30d": int(sessions_30d),

        "chat_msgs_7d": int(chat_msgs_7d),
        "chat_msgs_30d": int(chat_msgs_30d),
        "chat_avg_len_30d": float(chat_avg_len_30d),
        "chat_intent_rubric_ratio_30d": float(chat_intent_rubric_ratio_30d),
        "chat_intent_eval_ratio_30d": float(chat_intent_eval_ratio_30d),
        "chat_intent_practice_ratio_30d": float(chat_intent_practice_ratio_30d),
        "chat_intent_explain_ratio_30d": float(chat_intent_explain_ratio_30d),

        "pdc_generated_7d": int(pdc_generated_7d),
        "pdc_generated_30d": int(pdc_generated_30d),
        "pdc_has_rubric_ratio_30d": float(pdc_has_rubric_ratio_30d),
        "pdc_has_eval_ratio_30d": float(pdc_has_eval_ratio_30d),
        "pdc_practice_ratio_30d": float(pdc_practice_ratio_30d),
        "pdc_theory_ratio_30d": float(pdc_theory_ratio_30d),
        "pdc_production_ratio_30d": float(pdc_production_ratio_30d),

        "pdc_uploads_30d": int(pdc_uploads_30d),
        "pdc_downloads_30d": int(pdc_downloads_30d),
        "pdc_deletes_30d": int(pdc_deletes_30d),
        "pdc_iterative_index_30d": float(pdc_iterative_index_30d),

        "resources_suggested_30d": int(resources_suggested_30d),
        "resource_tech_ratio_30d": float(resource_tech_ratio_30d),

        "dim_saber_avg_30d": float(dim_saber_avg_30d),
        "dim_hacer_avg_30d": float(dim_hacer_avg_30d),
        "dim_ser_avg_30d": float(dim_ser_avg_30d),
        "dim_decidir_avg_30d": float(dim_decidir_avg_30d),

        "approval_ratio_30d": float(approval_ratio_30d),
        "friction_ratio_30d": float(friction_ratio_30d),
    }

def make_dataset(n: int) -> pd.DataFrame:
    return pd.DataFrame([gen_one_sample() for _ in range(n)])

df = make_dataset(12000)
df.head()

# CELDA 5
# Objetivo: pseudo-label FINAL (reglas cerradas + usa approval/friction para estilo).

MARGIN_THRESHOLD = 0.10
DATA_STRENGTH_DIVISOR = 60.0

def compute_data_strength(row: pd.Series) -> float:
    total = float(row["pdc_generated_30d"] + row["chat_msgs_30d"] + row["pdc_uploads_30d"])
    return clamp01(total / DATA_STRENGTH_DIVISOR)

def bootstrap_scores(row: pd.Series) -> Dict[str, float]:
    S_practico = 0.6*row["pdc_practice_ratio_30d"] + 0.4*row["chat_intent_practice_ratio_30d"]
    S_magistral = 0.6*row["pdc_theory_ratio_30d"] + 0.4*row["chat_intent_explain_ratio_30d"]
    S_evaluativo = 0.5*row["pdc_has_eval_ratio_30d"] + 0.3*row["pdc_has_rubric_ratio_30d"] + 0.2*row["chat_intent_eval_ratio_30d"]
    S_tecnologico = 0.7*row["resource_tech_ratio_30d"] + 0.3*min(1.0, row["resources_suggested_30d"]/10.0)
    S_reflexivo = 0.8*row["pdc_iterative_index_30d"] + 0.2*min(1.0, row["pdc_uploads_30d"]/5.0)

    # señal humana: fricción alta tiende a "iterativo" / "evaluativo"; aprobación alta tiende a cerrar rápido (más estructurado)
    S_reflexivo = clamp01(S_reflexivo + 0.15*row["friction_ratio_30d"])
    S_evaluativo = clamp01(S_evaluativo + 0.10*row["friction_ratio_30d"])
    S_magistral = clamp01(S_magistral + 0.10*row["approval_ratio_30d"])

    return {
        "PRACTICO_APLICADO": float(clamp01(S_practico)),
        "MAGISTRAL_ESTRUCTURADO": float(clamp01(S_magistral)),
        "EVALUATIVO": float(clamp01(S_evaluativo)),
        "TECNOLOGICO_INNOVADOR": float(clamp01(S_tecnologico)),
        "REFLEXIVO_ITERATIVO": float(clamp01(S_reflexivo)),
    }

def pick_style_with_fallback(row: pd.Series, scores: Dict[str, float]) -> str:
    items = sorted(scores.items(), key=lambda kv: kv[1], reverse=True)
    top1, top2 = items[0], items[1]
    margin = top1[1] - top2[1]

    if margin >= MARGIN_THRESHOLD:
        return top1[0]

    # fallback: si fricción alta -> reflexivo; si tech alto -> tecnológico; si pdc eval alto -> evaluativo
    if row["friction_ratio_30d"] >= 0.45:
        return "REFLEXIVO_ITERATIVO"
    if row["resource_tech_ratio_30d"] >= 0.55:
        return "TECNOLOGICO_INNOVADOR"
    if row["pdc_has_eval_ratio_30d"] >= 0.55 or row["chat_intent_eval_ratio_30d"] >= 0.55:
        return "EVALUATIVO"

    return top1[0]

labels = []
strengths = []
for _, r in df.iterrows():
    sc = bootstrap_scores(r)
    labels.append(pick_style_with_fallback(r, sc))
    strengths.append(compute_data_strength(r))

df["y_style"] = labels
df["y_idx"] = df["y_style"].map(STYLE_TO_IDX).astype(int)
df["data_strength"] = np.array(strengths, dtype=np.float32)

df["y_style"].value_counts()

# CELDA 6
# Objetivo: split + scaler (mean/std exportable).

X = df[FEATURE_NAMES].astype(np.float32).values
y = df["y_idx"].astype(np.int64).values

X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.30, random_state=SEED, stratify=y
)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, random_state=SEED, stratify=y_temp
)

mean = X_train.mean(axis=0)
std = X_train.std(axis=0)
std = np.where(std < 1e-6, 1.0, std)

def scale(arr: np.ndarray) -> np.ndarray:
    return (arr - mean) / std

X_train_s = scale(X_train)
X_val_s = scale(X_val)
X_test_s = scale(X_test)

print("Shapes:", X_train_s.shape, X_val_s.shape, X_test_s.shape)

# CELDA 7
# Objetivo: DataLoaders GPU.

class TabDataset(torch.utils.data.Dataset):
    def __init__(self, X: np.ndarray, y: np.ndarray):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.long)
    def __len__(self):
        return self.X.shape[0]
    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

BATCH_SIZE = 256
train_loader = torch.utils.data.DataLoader(TabDataset(X_train_s, y_train), batch_size=BATCH_SIZE, shuffle=True)
val_loader = torch.utils.data.DataLoader(TabDataset(X_val_s, y_val), batch_size=BATCH_SIZE, shuffle=False)
test_loader = torch.utils.data.DataLoader(TabDataset(X_test_s, y_test), batch_size=BATCH_SIZE, shuffle=False)

# CELDA 8
# Objetivo: modelo MLP FINAL (más serio) para producción.

class Red3MLP(nn.Module):
    def __init__(self, in_dim: int, num_classes: int):
        super().__init__()
        self.fc1 = nn.Linear(in_dim, 128)
        self.fc2 = nn.Linear(128, 64)
        self.fc3 = nn.Linear(64, 32)
        self.out = nn.Linear(32, num_classes)
        self.drop = nn.Dropout(p=0.25)
    def forward(self, x):
        x = F.relu(self.fc1(x)); x = self.drop(x)
        x = F.relu(self.fc2(x)); x = self.drop(x)
        x = F.relu(self.fc3(x)); x = self.drop(x)
        return self.out(x)

model = Red3MLP(INPUT_DIM, NUM_CLASSES).to(DEVICE)
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-3, weight_decay=1e-2)
criterion = nn.CrossEntropyLoss()

model

# CELDA 9
# Objetivo: entrenamiento FINAL con early stopping por F1 macro.

def eval_loader(m: nn.Module, loader) -> Tuple[float, float]:
    m.eval()
    ys, ps = [], []
    with torch.no_grad():
        for xb, yb in loader:
            xb = xb.to(DEVICE); yb = yb.to(DEVICE)
            logits = m(xb)
            pred = torch.argmax(logits, dim=1).cpu().numpy()
            ys.append(yb.cpu().numpy()); ps.append(pred)
    y_true = np.concatenate(ys)
    y_pred = np.concatenate(ps)
    return accuracy_score(y_true, y_pred), f1_score(y_true, y_pred, average="macro")

EPOCHS = 60
best_f1 = -1.0
best_state = None
patience = 8
pat = 0

for epoch in range(1, EPOCHS + 1):
    model.train()
    for xb, yb in train_loader:
        xb = xb.to(DEVICE); yb = yb.to(DEVICE)
        optimizer.zero_grad()
        logits = model(xb)
        loss = criterion(logits, yb)
        loss.backward()
        optimizer.step()

    val_acc, val_f1 = eval_loader(model, val_loader)
    print(f"Epoch {epoch:02d} | val_acc={val_acc:.4f} val_f1={val_f1:.4f}")

    if val_f1 > best_f1 + 1e-4:
        best_f1 = val_f1
        best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
        pat = 0
    else:
        pat += 1
        if pat >= patience:
            print("Early stopping.")
            break

model.load_state_dict(best_state)
print("Best val_f1:", best_f1)

# CELDA 10
# Objetivo: evaluación test (report + matriz).

def predict_proba(m: nn.Module, X_np: np.ndarray) -> np.ndarray:
    m.eval()
    with torch.no_grad():
        xb = torch.tensor(X_np, dtype=torch.float32).to(DEVICE)
        logits = m(xb).cpu().numpy()
        probs = np.exp(logits - logits.max(axis=1, keepdims=True))
        probs = probs / probs.sum(axis=1, keepdims=True)
    return probs

test_probs = predict_proba(model, X_test_s)
test_pred = test_probs.argmax(axis=1)

test_acc = float(accuracy_score(y_test, test_pred))
test_f1 = float(f1_score(y_test, test_pred, average="macro"))

print("Test Accuracy:", test_acc)
print("Test Macro-F1:", test_f1)
print("\nClassification report:\n")
print(classification_report(y_test, test_pred, target_names=STYLES))

cm = confusion_matrix(y_test, test_pred)
pd.DataFrame(cm, index=STYLES, columns=STYLES)

# CELDA 11
# Objetivo: calibración (ECE) + confianza.

ece = expected_calibration_error(test_probs, y_test, n_bins=12)
conf = test_probs.max(axis=1)

print("ECE:", float(ece))
print("Confidence mean:", float(conf.mean()))
print("Confidence min:", float(conf.min()))
print("Confidence max:", float(conf.max()))

# CELDA 12
# Objetivo: estabilidad simulada (JS divergence).

def simulate_time_series(base: Dict[str, float], steps: int = 10, noise: float = 0.06) -> List[Dict[str, float]]:
    series = []
    cur = base.copy()
    for _ in range(steps):
        nxt = cur.copy()
        for k in FEATURE_NAMES:
            v = float(nxt[k])
            if FEATURE_TYPES[k] == "float":
                if k == "chat_avg_len_30d":
                    v = max(20.0, v + float(np.random.normal(0, 25.0)))
                else:
                    v = clamp01(v + float(np.random.normal(0, noise)))
            else:
                v = max(0, int(round(v + float(np.random.normal(0, max(1.0, noise*12))))))
            nxt[k] = v
        series.append(nxt)
        cur = nxt
    return series

# scaler from training
mean = mean
std = std
def scale(arr: np.ndarray) -> np.ndarray:
    return (arr - mean) / std

base = gen_one_sample()
series = simulate_time_series(base)

X_series = np.array([[float(s[f]) for f in FEATURE_NAMES] for s in series], dtype=np.float32)
X_series_s = scale(X_series)

probs_series = predict_proba(model, X_series_s)
pred_series = [STYLES[int(p.argmax())] for p in probs_series]

js = []
for i in range(1, len(probs_series)):
    js.append(jensen_shannon(probs_series[i-1], probs_series[i]))

stability_js_mean = float(np.mean(js)) if js else 0.0
print("Pred styles:", pred_series)
print("JS divergence mean:", stability_js_mean)

# CELDA 13
# Objetivo: unit tests FINAL (schema, rangos, proba).

import unittest

class TestRed3Final(unittest.TestCase):
    def test_schema_frozen(self):
        self.assertEqual(INPUT_DIM, 30)
        self.assertEqual(FEATURE_NAMES[0], "active_days_7d")
        self.assertEqual(FEATURE_NAMES[-1], "friction_ratio_30d")

    def test_ratios_0_1_except_chat_len(self):
        sample = df.sample(400, random_state=SEED)
        for name, typ in FEATURES:
            if typ != "float":
                continue
            if name == "chat_avg_len_30d":
                self.assertTrue(np.all(sample[name].values >= 20.0))
            else:
                vals = sample[name].values
                self.assertTrue(np.all(vals >= -1e-6))
                self.assertTrue(np.all(vals <= 1.0 + 1e-6))

    def test_predict_probs(self):
        probs = predict_proba(model, X_test_s[:64])
        self.assertEqual(probs.shape, (64, NUM_CLASSES))
        self.assertTrue(np.allclose(probs.sum(axis=1), 1.0, atol=1e-4))

unittest.TextTestRunner().run(unittest.defaultTestLoader.loadTestsFromTestCase(TestRed3Final))

# CELDA 14
# Objetivo: export FINAL (modelo + schema + scaler + config + metrics) y ZIP.

ART_DIR = "/content/red3_artifacts"
os.makedirs(ART_DIR, exist_ok=True)

torch.save(model.state_dict(), os.path.join(ART_DIR, "red3_model_state.pt"))

feature_schema = {
    "feature_schema_version": FEATURE_SCHEMA_VERSION,
    "input_dim": INPUT_DIM,
    "features": [{"name": n, "type": FEATURE_TYPES[n]} for n in FEATURE_NAMES],
    "windows_days_supported": WINDOWS_DAYS,
}
with open(os.path.join(ART_DIR, "red3_feature_schema.json"), "w", encoding="utf-8") as f:
    json.dump(feature_schema, f, ensure_ascii=False, indent=2)

with open(os.path.join(ART_DIR, "red3_label_map.json"), "w", encoding="utf-8") as f:
    json.dump({"labels": STYLES}, f, ensure_ascii=False, indent=2)

with open(os.path.join(ART_DIR, "red3_scaler.json"), "w", encoding="utf-8") as f:
    json.dump({
        "type": "standard",
        "feature_schema_version": FEATURE_SCHEMA_VERSION,
        "mean": mean.tolist(),
        "std": std.tolist(),
    }, f, ensure_ascii=False, indent=2)

with open(os.path.join(ART_DIR, "red3_config.json"), "w", encoding="utf-8") as f:
    json.dump({
        "model_version": MODEL_VERSION,
        "feature_schema_version": FEATURE_SCHEMA_VERSION,
        "styles": STYLES,
        "windows_days_supported": WINDOWS_DAYS,
        "bootstrap": {
            "margin_threshold": 0.10,
            "data_strength_divisor": 60.0
        }
    }, f, ensure_ascii=False, indent=2)

with open(os.path.join(ART_DIR, "red3_metrics.json"), "w", encoding="utf-8") as f:
    json.dump({
        "test_accuracy": test_acc,
        "test_macro_f1": test_f1,
        "ece": float(ece),
        "stability_js_mean_simulated": stability_js_mean,
        "device": DEVICE
    }, f, ensure_ascii=False, indent=2)

print("Artifacts:", os.listdir(ART_DIR))

import shutil
zip_path = shutil.make_archive("/content/red3_artifacts", "zip", ART_DIR)
zip_path